root: ./data
dataset: cifar10_yuv
download: True
arch: oct_resnet20_small
alpha: 0.0
workers: 4
epochs: 200
batch-size: 128
lr: 0.1
lr-steps: [100, 150]
lr-warmup-epochs: 5
momentum: 0.9
weight-decay: 1e-4
print-freq: 10
